_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.11
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
aggregation:
    value: softmax-weighted voting
baseline_accuracy:
    value: 0.43
input:
    value: title + intro
k:
    value: 10
preliminary_accuracy:
    value: 0.6
retriever:
    value: Sentence-BERT (all-MiniLM-L6-v2)
